### Internal Spring Configuration
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${OAUTH2_KEYCLOAK_ALLURE_CLIENT_ID}
            client-secret: ${OAUTH2_KEYCLOAK_ALLURE_CLIENT_SECRET}
            scope: openid, profile, email
            client-name: keycloak
        provider:
          keycloak:
            issuer-uri: https://auth.indels.tech/realms/inDels

### App OAuth2 Security Configuration Toggle
app:
  security:
    enable-oauth2: true