name: Upload Release Asset

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fast checkout
        uses: actions/checkout@v2
      - name: Set RELEASE_VERSION
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:11}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.9.2
          arguments: ' -Pversion=${{ env.RELEASE_VERSION }} --stacktrace bootJar'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: allure-server-${{ env.RELEASE_VERSION }}.jar
          path: build/libs/allure-server-${{ env.RELEASE_VERSION }}.jar
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/allure-server-${{ env.RELEASE_VERSION }}.jar
          asset_name: allure-server.jar
          asset_content_type: application/jar
